clc; clear all; close all;
%% Example Database Manager
% the script explains how to get the physical characteristic of a sample in a DB

% Exemple 1 - Capacitor Database
% Call the database required, with the reference of the component
ReferenceSample = 1;
DatabaseSample = 'Capacitor';
CapaDB = DatabaseManager(DatabaseSample ,ReferenceSample);

Essai1 = struct(...
    'V' , CapaDB.voltage,...
    'C' , CapaDB.capacitance,...
    'Tmax', CapaDB.tMax,...
    'ESR' , CapaDB.ESR,...
    'ESL' , CapaDB.ESL,...
    'L' , CapaDB.length,...
    'Wi' , CapaDB.width,...
    'T' , CapaDB.thickness,...
    'W' , CapaDB.weight,...
    'Rth' , CapaDB.rTh,...
    'PN' , CapaDB.PN,...
    'VOl' , CapaDB.volume,...
    'MAN' , CapaDB.MAN);
