function [output_args] = updateDCfanDatabase( ~ )
currentPath = pwd;
pathToSave = getpref('OpenComp3d','path');
pathToSave = [pathToSave,'/OpenComp3d/DataBaseManager/ComponentManager/Fan'];
cd(pathToSave);

%% Import the data
[~,list,~] = xlsread('DCfan.xlsx','Fans','A1:AR1');
[~,~,raw] = xlsread('DCfan.xlsx','Fans','A3:AR17');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Exclude rows with blank cells
% To keep only workable data
J = any(cellfun(@(x) isempty(x) || (ischar(x) && all(x==' ')),raw),2); % Find row with blank cells
raw(J,:) = [];

%% Replace non-numeric cells with NaN
% % to make possible the import
% R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
% raw(R) = {NaN}; % Replace non-numeric cells

%% Import the Char and String Data

%% Create output variable

Fan = raw;

MatDCfan= struct(...
    'manufacturer', (Fan(:,1)),... 
    'name', (Fan(:,2)),...  
    'id',   (Fan(:,3)),...  
    'length',(Fan(:,4)),...
    'thickness', (Fan(:,5)),... 
    'volume', (Fan(:,6)),...
    'weight',(Fan(:,7)),...
    'noise', (Fan(:,8)),...
    'speed', (Fan(:,9)),...
    'vMin', (Fan(:,10)),...
    'voltage',(Fan(:,11)),...
    'vMax', (Fan(:,12)),...
    'price', (Fan(:,13)),...
    'power', (Fan(:,14)),...
    'Q1', (Fan(:,15)),...
    'Q2', (Fan(:,16)),...
    'Q3', (Fan(:,17)),...
    'Q4', (Fan(:,18)),...
    'Q5', (Fan(:,19)),...
    'Q6', (Fan(:,20)),...
    'Q7', (Fan(:,21)),...
    'Q8', (Fan(:,22)),...
    'Q9', (Fan(:,23)),...
    'Q10', (Fan(:,24)),...
    'Q11', (Fan(:,25)),...
    'Q12', (Fan(:,26)),...
    'Q13', (Fan(:,27)),...
    'Q14', (Fan(:,28)),...
    'Q15', (Fan(:,29)),...  
    'P1', (Fan(:,30)),...
    'P2', (Fan(:,31)),...
    'P3', (Fan(:,32)),...
    'P4', (Fan(:,33)),...
    'P5', (Fan(:,34)),...
    'P6', (Fan(:,35)),...
    'P7', (Fan(:,36)),...
    'P8', (Fan(:,37)),...
    'P9', (Fan(:,38)),...
    'P10', (Fan(:,39)),...
    'P11', (Fan(:,40)),...
    'P12', (Fan(:,41)),...
    'P13', (Fan(:,42)),...
    'P14', (Fan(:,43)),...
    'P15', (Fan(:,44))...       
);


%% Clear temporary variables
clearvars raw J R temp;
save MatDCfan
cd(currentPath);
end

